<rootWidget>:
    orientation: 'vertical'
    FloatLayout:
        Label:
            id: display
            text: root.textOnScreen
            font_size: 50
            size_hint: 1, 0.2
            pos_hint:{"x": 0, "top": 0.8}
            color: 1,1,1,1
        Label:
            id: plusM
            text: "+M"
            font_size: 30
            pos_hint:{"x": 0.4, "top": 1.45}
            color: 1,1,1,0
        Label:
            id: minusM
            text: "-M"
            font_size: 30
            pos_hint:{"x": 0.4, "top": 1.45}
            color: 1,1,1,0
        Button:
            text:"0"
            font_size: 50
            background_normal: ""
            background_color: 0.3, 0.3, 0.3, 1
            color: 1,1,1,1
            size_hint: 0.245, 0.125
            pos_hint: {"x" : 0, "y" : 0}
            on_press: root.clicked('0')
            on_release: root.displayText(self.text)
        Button:
            text:"."
            font_size: 50
            background_normal: ""
            background_color: 0.3, 0.3, 0.3, 1
            color: 1,1,1,1
            size_hint: 0.245, 0.125
            pos_hint: {"x": 0.25, "y": 0}
            on_press: root.clicked('.')
            on_release: root.displayText(self.text)
        Button:
            text:"BACK"
            font_size: 50
            background_normal: ""
            background_color: 0.3, 0.3, 0.3, 1
            color: 1,1,1,1
            size_hint: 0.245, 0.125
            pos_hint: {"x": 0.50, "y": 0}
            on_press: root.backButton()
        Button:
            text:"EXE"
            font_size: 50
            background_normal: ""
            background_color: 0.3, 0.3, 0.3, 1
            color: 1,1,1,1
            size_hint: 0.25, 0.125
            pos_hint: {"x": 0.75, "y": 0}
            on_press: root.displayAnswer()
        Button:
            text:"1"
            font_size: 50
            background_normal: ""
            background_color: 0.3, 0.3, 0.3, 1
            color: 1,1,1,1
            size_hint: 0.245, 0.125
            pos_hint: {"x": 0, "y": 0.13}
            on_press: root.clicked('1')
            on_release: root.displayText(self.text)
        Button:
            text:"2"
            font_size: 50
            background_normal: ""
            background_color: 0.3, 0.3, 0.3, 1
            color: 1,1,1,1
            size_hint: 0.245, 0.125
            pos_hint: {"x": 0.25, "y": 0.13}
            on_press: root.clicked('2')
            on_release: root.displayText(self.text)
        Button:
            text:"3"
            font_size: 50
            background_normal: ""
            background_color: 0.3, 0.3, 0.3, 1
            color: 1,1,1,1
            size_hint: 0.245, 0.125
            pos_hint: {"x": 0.5, "y": 0.13}
            on_press: root.clicked('3')
            on_release: root.displayText(self.text)
        Button:
            text:"÷"
            font_size: 50
            background_normal: ""
            background_color: 0.3, 0.3, 0.3, 1
            color: 1,1,1,1
            size_hint: 0.25, 0.125
            pos_hint: {"x": 0.75, "y": 0.13}
            on_press: root.clicked('/')
            on_release: root.displayText(self.text)
        Button:
            text:"4"
            font_size: 50
            background_normal: ""
            background_color: 0.3, 0.3, 0.3, 1
            color: 1,1,1,1
            size_hint: 0.245, 0.125
            pos_hint: {"x": 0, "y": 0.26}
            on_press: root.clicked('4')
            on_release: root.displayText(self.text)
        Button:
            text:"5"
            font_size: 50
            background_normal: ""
            background_color: 0.3, 0.3, 0.3, 1
            color: 1,1,1,1
            size_hint: 0.245, 0.125
            pos_hint: {"x": 0.25, "y": 0.26}
            on_press: root.clicked('5')
            on_release: root.displayText(self.text)
        Button:
            text:"6"
            font_size: 50
            background_normal: ""
            background_color: 0.3, 0.3, 0.3, 1
            color: 1,1,1,1
            size_hint: 0.245, 0.125
            pos_hint: {"x": 0.5, "y": 0.26}
            on_press: root.clicked('6')
            on_release: root.displayText(self.text)
        Button:
            text:"×"
            font_size: 50
            background_normal: ""
            background_color: 0.3, 0.3, 0.3, 1
            color: 1,1,1,1
            size_hint: 0.25, 0.125
            pos_hint: {"x": 0.75, "y": 0.26} 
            on_press: root.clicked('*')
            on_release: root.displayText(self.text)
        Button:
            text:"7"
            font_size: 50
            background_normal: ""
            background_color: 0.3, 0.3, 0.3, 1
            color: 1,1,1,1
            size_hint: 0.245, 0.125
            pos_hint: {"x": 0, "y": 0.39}  
            on_press: root.clicked('7')
            on_release: root.displayText(self.text)
        Button:
            text:"8"
            font_size: 50
            background_normal: ""
            background_color: 0.3, 0.3, 0.3, 1
            color: 1,1,1,1
            size_hint: 0.245, 0.125
            pos_hint: {"x": 0.25, "y": 0.39} 
            on_press: root.clicked('8')
            on_release: root.displayText(self.text)
        Button:
            text:"9"
            font_size: 50
            background_normal: ""
            background_color: 0.3, 0.3, 0.3, 1
            color: 1,1,1,1
            size_hint: 0.245, 0.125
            pos_hint: {"x": 0.5, "y": 0.39} 
            on_press: root.clicked('9')
            on_release: root.displayText(self.text)
        Button:
            text:"-"
            font_size: 50
            background_normal: ""
            background_color: 0.3, 0.3, 0.3, 1
            color: 1,1,1,1
            size_hint: 0.25, 0.125
            pos_hint: {"x": 0.75, "y": 0.39}
            on_press: root.clicked('-')
            on_release: root.displayText(self.text)
        Button:
            text:"AC"
            font_size: 50
            background_normal: ""
            background_color: 0.3, 0.3, 0.3, 1
            color: 1,1,1,1
            size_hint: 0.245, 0.125
            pos_hint: {"x": 0, "y": 0.52} 
            on_press: root.clearScreen()
            on_release: plusM.color = 1,1,1,0
            on_release: minusM.color = 1,1,1,0
        Button:
            text:"+M"
            font_size: 50
            background_normal: ""
            background_color: 0.3, 0.3, 0.3, 1
            color: 1,1,1,1
            size_hint: 0.245, 0.125
            pos_hint: {"x": 0.25, "y": 0.52} 
            on_press: root.clickedM('+')
            on_release: minusM.color = 1,1,1,0
            on_release: plusM.color = 1,1,1,1
        Button:
            text:"-M"
            font_size: 50
            background_normal: ""
            background_color: 0.3, 0.3, 0.3, 1
            color: 1,1,1,1
            size_hint: 0.245, 0.125
            pos_hint: {"x": 0.5, "y": 0.52} 
            on_press: root.clickedM('-')
            on_release: plusM.color = 1,1,1,0
            on_release: minusM.color = 1,1,1,1
        Button:
            text:"+"
            font_size: 50
            background_normal: ""
            background_color: 0.3, 0.3, 0.3, 1
            color: 1,1,1,1
            size_hint: 0.25, 0.125
            pos_hint: {"x": 0.75, "y": 0.52} 
            on_press: root.clicked('+') 
            on_release: root.displayText(self.text)
        